In [17]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss= torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [18]:
print(x.requires_grad, y.requires_grad, w.requires_grad, b.requires_grad, z.requires_grad, loss.requires_grad)
print("Gradient function for z = {}".format(z.grad_fn))
# print("Gradient function for loss = {}".format(loss.grad_fn))

False False True True True True
Gradient function for z = <AddBackward0 object at 0x7fdea0094df0>


In [4]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0970, 0.2518, 0.1457],
        [0.0970, 0.2518, 0.1457],
        [0.0970, 0.2518, 0.1457],
        [0.0970, 0.2518, 0.1457],
        [0.0970, 0.2518, 0.1457]])
tensor([0.0970, 0.2518, 0.1457])


In [5]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [19]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [38]:
inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
print(out)
out.backward(torch.ones_like(out), retain_graph=True)
print("First call\n{}".format(inp.grad))
out.backward(torch.ones_like(out), retain_graph=True)
print("Second call\n{}".format(inp.grad))
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print("\nCall after zeroing gradient\n{}".format(inp.grad))

tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<TBackward0>)
First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradient
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
